pipeline {
    agent any

    environment {
        COMPOSE_PATH = "docker-compose.app.yml"
        BACKEND_IMAGE_NAME = "backend:latest"
    }

    stages {
        stage('Checkout') {
            steps {
                echo "GitLab에서 코드 클론 중..."
                withCredentials([string(credentialsId: 'gitlab-token', variable: 'GITLAB_TOKEN')]) {
                    sh '''
                        git clone -b dev/INF https://${GITLAB_TOKEN}@lab.ssafy.com/s12-bigdata-recom-sub1/square.git
                    '''
            }
        }

        stage('Build Backend') {
            steps {
                echo "백엔드 gradle 빌드 시작"
                dir('backend') {
                    sh './gradlew clean build -x test'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "백엔드 Docker 이미지 빌드"
                sh '''
                    docker build \
                      -t ${BACKEND_IMAGE_NAME} \
                      -f devops/docker/backend.Dockerfile \
                      .
                '''
            }
        }

        stage('Deploy App') {
            steps {
                echo "앱 재배포 (docker-compose.app.yml)"
                sh '''
                  docker-compose -f ${COMPOSE_PATH} down
                  docker-compose -f ${COMPOSE_PATH} up -d --build
                '''
            }
        }
    }

    post {
        success {
            echo "배포 성공"
        }
        failure {
            echo "배포 실패. 로그를 확인하세요."
        }
    }
}
