pipeline {
    agent any

    environment {
        GIT_REPO = "https://52.141.26.96/s12-bigdata-recom-sub1/square.git"
        GIT_HOST = "lab.ssafy.com"
        GIT_BRANCH = "deploy" // 또는 dev/BE 등
        TOKEN = credentials('gitlab-credentials') // Personal Access Token
    }

    stages {
        stage('Manual Clone') {
            steps {
                echo "Git 저장소 직접 clone 시도"
                sh '''
                    rm -rf square || true
                    git -c http.extraHeader="Authorization: Bearer ${TOKEN}" \
                        -c http.sslVerify=false \
                        clone --branch ${GIT_BRANCH} ${GIT_REPO} square

                    cd square
                    ls -al
                '''
            }
        }

        stage('Build Backend') {
            steps {
                echo "백엔드 gradle 빌드 시작"
                dir('backend') {
                    sh './gradlew clean build -x test'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "백엔드 Docker 이미지 빌드"
                sh '''
                    docker build \
                      -t ${BACKEND_IMAGE_NAME} \
                      -f devops/docker/backend.Dockerfile \
                      .
                '''
            }
        }

        stage('Deploy App') {
            steps {
                echo "앱 재배포 (docker-compose.app.yml)"
                sh '''
                  docker-compose -f ${COMPOSE_PATH} down
                  docker-compose -f ${COMPOSE_PATH} up -d --build
                '''
            }
        }
    }

    post {
        success {
            echo "배포 성공"
        }
        failure {
            echo "배포 실패. 로그를 확인하세요."
        }
    }
}
